# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

debug <- function(s) {
    invisible(.Call(`_tl_debug`, s))
}

info <- function(s) {
    invisible(.Call(`_tl_info`, s))
}

